version: '3.9'

services:
  db:
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
      
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'postgres@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'password'
    ports:
      - 80:80
    depends_on:
      - db

volumes:
  postgres-data:

